CREATE DATABASE IF NOT EXISTS square_db;
USE square_db;

CREATE TABLE IF NOT EXISTS square (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sideLength DECIMAL(10, 2) NOT NULL,
  perimeter DECIMAL(10, 2) NOT NULL,
  area DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  description TEXT
);
